### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by Faurby** [Faurby/BlackOps#7]
Test everything!

Services
Controllers
Integration testing maybe

**Comment by FrederikRothe** [comment]
Figure out a way to create a Mock-DB to test on. 

Testing requires you to create a Options object since this is passed on to both the UsersService and via. that the Controller. 
This can also be mocked, check link below:
https://www.niceonecode.com/question/20643/net-core-unit-testing-mock-ioptions

**Comment by Caspar1106** [comment]
Unit testing has started -> UnitTesting branch

**Comment by Caspar1106** [comment]
UserController Assigned to me

**Comment by Faurby** [comment]
Done:
UsersController
MessagesController

Need:
UsersService
MessagesService

Figure out mock / temp in memory maybe mongoDB
